'\" t
.\"     Title: comodit
.\"    Author: Daniel Bartz <daniel.bartz@guardis.com>
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 09/28/2012
.\"    Manual: Command Line User Interface Guide
.\"    Source: Guardis
.\"  Language: English
.\"
.TH "COMODIT" "1" "09/28/2012" "Guardis" "Command Line User Interface Gu"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
comodit \- ComodIT command\-line interface
.SH "SYNOPSIS"
.HP \w'/usr/bin/comodit\ 'u
/usr/bin/comodit [\-h\ |\ \-\-help] [\-f\ FILE\ |\-\-file\ FILE] [\-j\ FILE\ |\-\-json\ FILE] [\-d\ |\ \-\-default] [\-t\ |\ \-\-test] [\-\-raw] [\-\-flavor\ FLAVOR] [\-\-skip\-chown] [\-\-skip\-chmod] [\-\-skip\-conflict] [\-\-dry\-run] [\-\-api\ URL] [\-\-user\ USERNAME] [\-\-pass\ PASSWORD] [\-\-templates\ PATH] [\-\-profile\ NAME] [\-\-force] [\-\-debug] [\-\-version] {resource} [sub\-resources\ \&...] {action} [\&...]
.SH "DESCRIPTION"
.PP
ComodIT is a global, integrated and centralized platform that eases the management of Linux systems and cloud provisioning (i\&.e\&. the instantiation of ready\-to\-use VMs)\&.
.PP
ComodIT actually manages different types of resources representing high\-level concepts:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
users: a ComodIT\-level user that is able to access the system\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
organizations: an organization typically encompasses the resources that may be managed/used by a group of users\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
environments: an environment is defined in the context of an organization\&. It represents a group of servers having common properties, access rights, etc\&. For example, it may be interesting to define a test environment containing servers used by developers to test their software and a production environment containing servers hosting the software accessed by customers\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
hosts: a host is defined in the context of an environment\&. It represents the description of a server: operating system, applications, etc\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
applications: an application is defined in the context of an organization and represents a software solution that may be installed on a host\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
platforms: a platform is defined in the context of an organization\&. It represents a way to \*(Aqinstantiate\*(Aq (e\&.g\&. create a virtual machine) a server\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
distributions: a distribution is defined in the context of an organization\&. It represents an operating system to install on a host after it was instantiated\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
flavors: a flavor is a template of distribution\&. Flavors are read\-only resources\&.
.RE
.PP
ComodIT client allows to handle ComodIT resources by interacting with ComodIT server through its REST API\&. Basically, a target resource type, an action and a resource identifier \-\-sometimes additional parameters\-\- have to be provided\&. The action is then applied on given resource\&.
.PP
Instead of a resource type, a service name can be given\&. Again, an action and some parameters may be provided, leading to one or several interactions with the server\&.
.PP
Some resources, so called sub\-resources, are \*(Aqincorporated\*(Aq into others i\&.e\&. they must be accessed through a containing resource\&. For example, the following sub\-resources are common to several resources:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
parameters: a value expected by an application, a distribution or a platform\&. This value is identified by a key\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
settings: a key\-value pair that may be associated to an organization, an environment, a host, as well as an application, a distribution or a platform associated to a given host\&. The key should match a parameter key and, therefore, provide an expected value\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
files: a file that may be associated to a distribution, a platform or an application\&.
.RE
.PP
When a sub\-resource must be targeted, its type is composed of the containing resource type and the sub\-resource\*(Aqs type\&. There may be several levels of resources\&.
.PP
Available (sub)resources and services are described in more details below\&.
.PP
Examples are given at the end of this page\&.
.SH "COMODIT RESOURCES"
.SS "Introduction"
.PP
Most resources feature exactly the same actions which share the same semantic:
.PP
list ID
.RS 4
Lists resources of given type associated to given resource (identified by ID)\&.
.RE
.PP
show ID [\-\-raw]
.RS 4
Prints informations about a resource on standard output\&. ID is a resource\*(Aqs identifier and depends on resource\*(Aqs type\&. \-\-raw option causes the client to print the JSON representation of the resource\&.
.RE
.PP
add [\-f FILE|\-\-file FILE|\-j JSON|\-\-json JSON] [ID]
.RS 4
Creates a new resource, potentially in the context of a containing resource whose ID must then be given\&. Without any option, a JSON template is opened with editor defined by environment variables VISUAL or EDITOR\&. If these variables are not defined, \*(Aqnotepad\&.exe\*(Aq is used on Windows and \*(Aqvi\*(Aq on other systems\&. If opened template is saved, a new resource is created using provided data\&.
.sp
If \*(Aq\-f\*(Aq or \*(Aq\-\-file\*(Aq options is defined, the resource is created using JSON description from given file\&.
.sp
If \*(Aq\-j\*(Aq or \*(Aq\-\-json\*(Aq options is defined, the resource is created using JSON description read from standard input\&.
.RE
.PP
update ID [\-f FILE|\-\-file FILE|\-j JSON|\-\-json JSON] [\-\-raw]
.RS 4
Updates a resource\&. ID is a resource\*(Aqs identifier and depends on resource\*(Aqs type\&. By default, resource\*(Aqs JSON representation is opened with editor defined by environment variables VISUAL or EDITOR\&. If these variables are not defined, \*(Aqnotepad\&.exe\*(Aq is used on Windows and \*(Aqvi\*(Aq on other systems\&. If opened template is saved, resource is updated using provided data\&. Updated data are then shown\&. \-\-raw option causes the client to print JSON representation of given resource\&.
.sp
If \*(Aq\-f\*(Aq or \*(Aq\-\-file\*(Aq options is defined, user is updated using JSON description from given file\&.
.sp
If \*(Aq\-j\*(Aq or \*(Aq\-\-json\*(Aq options is defined, user is updated using JSON description read from standard input\&.
.RE
.PP
delete ID
.RS 4
Deletes a resource\&. ID is a resource\*(Aqs identifier and depends on resource\*(Aqs type\&.
.RE
.PP
Below, actions for each (sub)resource type are detailed\&.
.SS "files"
.PP
A file is a sub\-resource\&. It is uniquely identified by its name and the identifier of the resource it is part of\&. Therefore, \*(Aqlist\*(Aq and \*(Aqadd\*(Aq take the containing resource identifier as argument where \*(Aqshow\*(Aq, \*(Aqupdate\*(Aq and \*(Aqdelete\*(Aq the file identifier\&.
.PP
Files feature 2 additional actions:
.PP
show\-content ID
.RS 4
Prints the content of the file on standard output\&.
.RE
.PP
set\-content ID PATH
.RS 4
Uploads the content of local file PATH to file identified by ID\&.
.RE
.SS "parameters"
.PP
A parameter is a sub\-resource of platform, distribution and application\&. It is uniquely identified by its name and the identifier of the resource it is part of\&. Therefore, \*(Aqlist\*(Aq and \*(Aqadd\*(Aq take the containing resource identifier as argument where \*(Aqshow\*(Aq, \*(Aqupdate\*(Aq and \*(Aqdelete\*(Aq the file identifier\&.
.SS "sync"
.PP
Sync is a sub\-resource of distribution and application\&. It allows to synchronize local files describing an entity with an actual entity on ComodIT\&. The files describing an entity may be obtained using \*(Aqexport\*(Aq action (see below)\&. Only 2 actions are available: \*(Aqpull\*(Aq and \*(Aqpush\*(Aq\&.
.PP
pull ORG_NAME NAME PATH [\-\-dry\-run]
.RS 4
Updates local files with data from entity\&. Local files may be created, deleted and/or updated\&. Entity stays untouched\&. \*(Aq\-\-dry\-run\*(Aq option allows to print actions that will be taken without applying them\&.
.RE
.PP
push ORG_NAME NAME PATH [\-\-dry\-run]
.RS 4
Updates entity with local files\&. Entity is updated but local files stay untouched\&. \*(Aq\-\-dry\-run\*(Aq option allows to print actions that will be taken without applying them\&.
.RE
.SS "settings"
.PP
A setting is a sub\-resource of organization, environment, host, distribution, platform, application context, platform context and distribution context\&. It is uniquely identified by its name and the identifier of the resource it is part of\&. Therefore, \*(Aqlist\*(Aq and \*(Aqadd\*(Aq take the containing resource identifier as argument where \*(Aqshow\*(Aq, \*(Aqupdate\*(Aq and \*(Aqdelete\*(Aq the file identifier\&.
.SS "platforms"
.PP
A platform is uniquely identified by its name and the name of the organization it is part of\&. Therefore, \*(Aqlist\*(Aq and \*(Aqadd\*(Aq take an organization name as argument where \*(Aqshow\*(Aq, \*(Aqupdate\*(Aq and \*(Aqdelete\*(Aq an organization name and a platform name\&.
.PP
Supplementary options are available when adding a platform:
.PP
\*(Aq\-\-default\*(Aq or \*(Aq\-d\*(Aq
.RS 4
if the option is provided, platform\*(Aqs driver configures it i\&.e\&. adds required files and settings\&.
.RE
.PP
\*(Aq\-\-test\*(Aq or \*(Aq\-t\*(Aq
.RS 4
if the option is provided, platform\*(Aqs driver validates given settings\&.
.RE
.PP
A platform has 3 sub\-resources:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
files
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
parameters
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
settings
.RE
.PP
Platforms feature additional actions:
.PP
clone ORG_NAME PLAT_NAME CLONE_NAME
.RS 4
Creates a copy of given platform\&.
.RE
.PP
import [PATH]
.RS 4
Platform is imported from given folder\&.
.RE
.SS "applications"
.PP
An application is uniquely identified by its name and the name of the organization it is part of\&. Therefore, \*(Aqlist\*(Aq and \*(Aqadd\*(Aq take an organization name as argument where \*(Aqshow\*(Aq, \*(Aqupdate\*(Aq and \*(Aqdelete\*(Aq an organization name and an application name\&.
.PP
An application has 3 sub\-resources:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
files
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
parameters
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
sync
.RE
.PP
Applications feature additional actions:
.PP
clone ORG_NAME APP_NAME CLONE_NAME
.RS 4
Creates a copy of given application\&.
.RE
.PP
import [PATH]
.RS 4
Application is imported from given folder\&.
.RE
.SS "flavors"
.PP
A flavor is uniquely identified by its name\&. Therefore \*(Aqlist\*(Aq does not take any argument and \*(Aqshow\*(Aq takes a flavor name\&. As flavors are read\-only resources, \*(Aqadd\*(Aq, \*(Aqupdate\*(Aq and \*(Aqdelete\*(Aq actions are not available\&.
.SS "distributions"
.PP
A distribution is uniquely identified by its name and the name of the organization it is part of\&. Therefore, \*(Aqlist\*(Aq and \*(Aqadd\*(Aq take an organization name as argument where \*(Aqshow\*(Aq, \*(Aqupdate\*(Aq and \*(Aqdelete\*(Aq an organization name and a distribution name\&.
.PP
A supplementary option is available when adding a distribution: \*(Aq\-\-flavor FLAVOR\*(Aq\&. It allows the user to select the flavor of created distribution, letting the server adding default files, parameters and/or settings\&. See \*(Aqflavors\*(Aq resource\&.
.PP
A distribution has 4 sub\-resources:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
files
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
parameters
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
settings
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
sync
.RE
.PP
Distributions feature an additional action:
.PP
clone ORG_NAME DIST_NAME CLONE_NAME
.RS 4
Creates a copy of given distribution\&.
.RE
.PP
import [PATH]
.RS 4
Distribution is imported from given folder\&.
.RE
.SS "users"
.PP
A user is uniquely identified by its name\&. Therefore, \*(Aqlist\*(Aq and \*(Aqadd\*(Aq take no argument where \*(Aqshow\*(Aq, \*(Aqupdate\*(Aq and \*(Aqdelete\*(Aq take a user name\&.
.SS "organizations"
.PP
An organization is uniquely identified by its name\&. Therefore, \*(Aqlist\*(Aq and \*(Aqadd\*(Aq take no argument where \*(Aqshow\*(Aq, \*(Aqupdate\*(Aq and \*(Aqdelete\*(Aq take an organization name\&.
.PP
An organization has 2 sub\-resources:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
groups
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
settings
.RE
.PP
An organization has user groups that allow to implement a simple access control: members of \*(Aqadmin\*(Aq group have full access on the organization; members of \*(Aqusers\*(Aq group have full access on the resources of the organization\&. In particular, members of \*(Aqusers\*(Aq group cannot add or remove users from the organization but \*(Aqadmin\*(Aq users can\&.
.PP
Group sub\-resource allows to \*(Aqlist\*(Aq, \*(Aqshow\*(Aq and \*(Aqupdate\*(Aq an organization\*(Aqs users groups\&. \*(Aqadd\*(Aq and \*(Aqdelete\*(Aq actions are not yet available\&.
.PP
Organizations feature 3 additional actions:
.PP
export ORG_NAME [PATH] [\-\-force]
.RS 4
Organization is exported onto disk in given folder\&. If no folder is given, a folder with organization\*(Aqs name is created and data written into it\&. If \-\-force option is set, data already present in output folder are overwritten\&.
.RE
.PP
import [PATH] [\-\-force] [\-\-skip\-conflicts] [\-\-dry\-run]
.RS 4
Organization is imported from given folder\&. If \-\-force option is set, data already present on server are updated\&. \-\-skip\-conflicts implies that data already present are ignored\&. With \-\-dry\-run, actions are not actually performed but displayed on standard output\&.
.RE
.PP
audit ORG_NAME
.RS 4
Prints audit logs for this organization\&.
.RE
.SS "environments"
.PP
An environment is uniquely identified by its name and the name of the organization it is part of\&. Therefore, \*(Aqlist\*(Aq and \*(Aqadd\*(Aq take an organization name as argument where \*(Aqshow\*(Aq, \*(Aqupdate\*(Aq and \*(Aqdelete\*(Aq an organization name and an environment name\&.
.PP
An environment has \*(Aqsettings\*(Aq sub\-resource\&.
.PP
Environments feature 2 additional actions:
.PP
clone ORG_NAME ENV_NAME CLONE_NAME
.RS 4
Creates a copy of given environment\&.
.RE
.PP
audit ORG_NAME ENV_NAME
.RS 4
Prints audit logs for this environment\&.
.RE
.SS "hosts"
.PP
A host is uniquely identified by its name, the name of the environment it is part of and the name of the environment\*(Aqs organization\&. Therefore, \*(Aqlist\*(Aq and \*(Aqadd\*(Aq take an organization name and an environment name as arguments where \*(Aqshow\*(Aq, \*(Aqupdate\*(Aq and \*(Aqdelete\*(Aq take an organization name, an environment name and a host name\&.
.PP
A host has 5 sub\-resources:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
instance
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
applications
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
platform
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
distribution
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
live
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
compliance
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
settings
.RE
.PP
\*(Aqinstance\*(Aq sub\-resource allows to handle the instance of a given host\&. It defines following actions:
.PP
start ORG_NAME ENV_NAME HOST_NAME
.RS 4
Starts the instance\&.
.RE
.PP
poweroff ORG_NAME ENV_NAME HOST_NAME
.RS 4
Powers the instance off\&.
.RE
.PP
pause ORG_NAME ENV_NAME HOST_NAME
.RS 4
Pauses the instance\&.
.RE
.PP
shutdown ORG_NAME ENV_NAME HOST_NAME
.RS 4
Shuts the instance down\&.
.RE
.PP
show ORG_NAME ENV_NAME HOST_NAME
.RS 4
Shows an instance\*(Aqs details\&.
.RE
.PP
resume ORG_NAME ENV_NAME HOST_NAME
.RS 4
Resumes the execution of an instance\&.
.RE
.PP
properties ORG_NAME ENV_NAME HOST_NAME
.RS 4
Displayes the properties of an instance\&.
.RE
.PP
delete ORG_NAME ENV_NAME HOST_NAME
.RS 4
Deletes an instance\&.
.RE
.PP
\*(Aqapplications\*(Aq sub\-resource allows to handle the applications of a given host\&. It defines following actions:
.PP
show ORG_NAME ENV_NAME HOST_NAME APP_NAME
.RS 4
Shows the details of an application context\&.
.RE
.PP
list ORG_NAME ENV_NAME HOST_NAME
.RS 4
Lists the applications installed on a given host\&.
.RE
.PP
install ORG_NAME ENV_NAME HOST_NAME APP_NAME [\-f FILE|\-\-file FILE|\-j JSON|\-\-json JSON]
.RS 4
Installs an application on a host\&.
.RE
.PP
uninstall ORG_NAME ENV_NAME HOST_NAME APP_NAME
.RS 4
Uninstalls an application from a host\&.
.RE
.PP
render\-file ORG_NAME ENV_NAME HOST_NAME APP_NAME FILE_NAME
.RS 4
Displays the rendering of a file of an installed application\&.
.RE
.PP
link ORG_NAME ENV_NAME HOST_NAME APP_NAME FILE_NAME
.RS 4
Displays a one\-time URL for given file\&.
.RE
It also has the \*(Aqsettings\*(Aq sub\-resources\&.
.PP
\*(Aqdistribution\*(Aq sub\-resource allows to handle the distribution of a given host\&. It defines following actions:
.PP
show ORG_NAME ENV_NAME HOST_NAME
.RS 4
Shows the details of a distribution context\&.
.RE
.PP
add ORG_NAME ENV_NAME HOST_NAME [\-f FILE|\-\-file FILE|\-j JSON|\-\-json JSON]
.RS 4
Sets the distribution associated to given host\&.
.RE
.PP
delete ORG_NAME ENV_NAME HOST_NAME
.RS 4
Unsets the distribution associated to given host\&.
.RE
.PP
render\-file ORG_NAME ENV_NAME HOST_NAME FILE_NAME
.RS 4
Displays the rendering of a file of the distribution\&.
.RE
.PP
link ORG_NAME ENV_NAME HOST_NAME FILE_NAME
.RS 4
Displays a one\-time URL for given file\&.
.RE
It also has the \*(Aqsettings\*(Aq sub\-resources\&.
.PP
\*(Aqplatform\*(Aq sub\-resource allows to handle the platform of a given host\&. It defines following actions:
.PP
show ORG_NAME ENV_NAME HOST_NAME
.RS 4
Shows the details of a platform context\&.
.RE
.PP
add ORG_NAME ENV_NAME HOST_NAME [\-f FILE|\-\-file FILE|\-j JSON|\-\-json JSON]
.RS 4
Sets the platform associated to given host\&.
.RE
.PP
delete ORG_NAME ENV_NAME HOST_NAME APP_NAME
.RS 4
Unsets the platform associated to given host\&.
.RE
.PP
render\-file ORG_NAME ENV_NAME HOST_NAME APP_NAME FILE_NAME
.RS 4
Displays the rendering of a file of the platform\&.
.RE
.PP
link ORG_NAME ENV_NAME HOST_NAME FILE_NAME
.RS 4
Displays a one\-time URL for given file\&.
.RE
It also has the \*(Aqsettings\*(Aq sub\-resources\&.
.PP
\*(Aqlive\*(Aq sub\-resource allows to execute some operations related to an application\*(Aqs resource directly on the machine associated to this host:
.PP
install\-package ORG_NAME ENV_NAME HOST_NAME APP_NAME PACKAGE_RES_NAME
.RS 4
(Re)installs package on machine\&.
.RE
.PP
restart\-service ORG_NAME ENV_NAME HOST_NAME APP_NAME SERVICE_RES_NAME
.RS 4
Re\-starts service on machine\&.
.RE
.PP
update\-file ORG_NAME ENV_NAME HOST_NAME APP_NAME FILE_RES_NAME
.RS 4
Updates file on machine\&.
.RE
.PP
\*(Aqcompliance\*(Aq sub\-resource allows to handle compliance errors\&. It defines following actions:
.PP
show ORG_NAME ENV_NAME HOST_NAME applications/APP_NAME/RES_TYPE/RES_NAME
.RS 4
Shows the details of a compliance error\&. RES_TYPE is one of \*(Aqfiles\*(Aq, \*(Aqservices\*(Aq or \*(Aqpackages\*(Aq\&.
.RE
.PP
list ORG_NAME ENV_NAME HOST_NAME
.RS 4
Lists the compliance errors of this host\&.
.RE
.PP
delete ORG_NAME ENV_NAME HOST_NAME applications/APP_NAME/RES_TYPE/RES_NAME
.RS 4
Deletes a compliance error\&. RES_TYPE is one of \*(Aqfiles\*(Aq, \*(Aqservices\*(Aq or \*(Aqpackages\*(Aq\&.
.RE
.PP
delete\-all ORG_NAME ENV_NAME HOST_NAME FILE_NAME
.RS 4
Deletes all compliance errors\&.
.RE
.PP
Hosts feature additional actions:
.PP
render\-tree ORG_NAME ENV_NAME HOST_NAME PATH
.RS 4
Renders all application files associated to given host\&. Rendered files are output in given folder\&.
.RE
.PP
changes ORG_NAME ENV_NAME HOST_NAME
.RS 4
Displays pending changes for given host\&.
.RE
.PP
clear\-changes ORG_NAME ENV_NAME HOST_NAME
.RS 4
Clears pending changes for given host\&.
.RE
.PP
provision ORG_NAME ENV_NAME HOST_NAME
.RS 4
Provisions (i\&.e\&. instantiates and configures) given host\&. This action creates the instance of the host\&.
.RE
.PP
audit ORG_NAME ENV_NAME HOST_NAME
.RS 4
Prints audit logs for this host\&.
.RE
.SH "OPTIONS"
.PP
\-f FILE |\-\-file FILE
.RS 4
Provides a JSON description in a file (see \*(Aqadd\*(Aq and \*(Aqupdate\*(Aq actions)\&.
.RE
.PP
\-j FILE |\-\-json FILE
.RS 4
Provides a JSON description via standard input (see \*(Aqadd\*(Aq and \*(Aqupdate\*(Aq actions)\&.
.RE
.PP
\-d | \-\-default
.RS 4
Let driver add required files and/or settings to newly created platform\&.
.RE
.PP
\-t | \-\-test
.RS 4
Let driver test provided settings of newly created platform\&.
.RE
.PP
\-\-skip\-conflict
.RS 4
If this option is set, conflicting resources are not imported during organization import\&.
.RE
.PP
\-\-dry\-run
.RS 4
On organization import, sync pull or sync push, do not actually import anything but display actions that would be executed\&.
.RE
.PP
\-\-raw
.RS 4
JSON representation is dumped to standard output instead of a more \*(Aquser friendly\*(Aq presentation\&. (see \*(Aqshow\*(Aq and \*(Aqupdate\*(Aq actions)\&.
.RE
.PP
\-\-skip\-chown
.RS 4
Skips ownership setting on files (see \*(Aqtree\*(Aq on rendering)\&.
.RE
.PP
\-\-skip\-chmod
.RS 4
Skips mode setting on files (see \*(Aqtree\*(Aq on rendering)\&.
.RE
.PP
\-\-api URL
.RS 4
Sets the URL of ComodIT server\*(Aqs API\&.
.RE
.PP
\-\-user USERNAME
.RS 4
Sets the user name to use for authentication\&.
.RE
.PP
\-\-pass PASSWORD
.RS 4
Sets the password to use for authentication\&.
.RE
.PP
\-\-templates PATH
.RS 4
Sets templates directory\&. Templates are used when creating a resource in interactive mode (see \*(Aqadd\*(Aq)\&.
.RE
.PP
\-\-profile NAME
.RS 4
Sets connection profile\&. A connection profile encompasses an URL to a ComodIT server API, a user name and a password\&. Profiles are defined in configuration file\&. NAME is the name of a profile of the configuration file\&.
.RE
.PP
\-\-debug
.RS 4
Prints complete stack trace in case of error\&. Only error message is displayed by default\&.
.RE
.PP
\-\-version
.RS 4
Prints version information\&.
.RE
.SH "CONFIGURATION FILES"
.PP
Client reads connection informations from a configuration file\&. Following files are parsed (files are listed in increasing order of priority):
.RS 4
\&./conf/comodit\-client\&.conf
.RE
.RS 4
~/\&.comoditrc
.RE
.RS 4
/etc/comodit\-client/comodit\-client\&.conf
.RE
.PP
A configuration file should contain one or serveral profiles\&. A profile is the URL of a ComodIT server\*(Aqs API, a user name and a password\&. Option \-\-profile can be used to select a particular profile\&. The configuration file also contains the profile to use by default, when no profile is selected\&.
.PP
Here is an example of configuration file:
.RS 4
 
.RE
.RS 4
[client]
.RE
.RS 4
default_profile = default
.RE
.RS 4
 
.RE
.RS 4
[default]
.RE
.RS 4
api = http://localhost:8000/api
.RE
.RS 4
username = admin
.RE
.RS 4
password = secret
.RE
.PP
By default, profile with name \*(Aqdefault\*(Aq is used\&. This profile defines \*(Aqhttp://localhost:8000/api\*(Aq as the API URL (see \-\-api option), \*(Aqadmin\*(Aq as user name (see \-\-user option) and \*(Aqsecret\*(Aq as password (see \-\-pass option)\&.
.SH "EXAMPLES"
.SS "List available resources"
.PP
Following command shows the list of organizations the user has access to (i\&.e\&. is member of):
.RS 4
 
.RE
.RS 4
comodit organizations list
.RE
.SS "Show a resource\*(Aqs details"
.PP
Following command shows the details of a distribution DIST from organization ORG the user has access to (i\&.e\&. is member of):
.RS 4
 
.RE
.RS 4
comodit distributions show ORG DIST
.RE
.SS "Provision a host"
.PP
Following command provisions host HOST part of environment ENV from organization ORG:
.RS 4
 
.RE
.RS 4
comodit hosts provision ORG ENV HOST
.RE
.SS "Handle a host\*(Aqs instance"
.PP
Following command starts the instance (i\&.e\&. VM) associated to host HOST part of environment ENV from organization ORG:
.RS 4
 
.RE
.RS 4
comodit hosts instance start ORG ENV HOST
.RE
.SH "AUTHORS"
.PP
\fBDaniel Bartz\fR <\&daniel.bartz@guardis.com\&>
.br
Guardis
.RS 4
Author.
.RE
.PP
\fBSebastien Caps\fR <\&sebastien.caps@guardis.com\&>
.br
Guardis
.RS 4
Author.
.RE
.PP
\fBGérard Dethier\fR <\&gerard.dethier@guardis.com\&>
.br
Guardis
.RS 4
Author.
.RE
.PP
\fBLaurent Eschenauer\fR <\&laurent.eschenauer@guardis.com\&>
.br
Guardis
.RS 4
Author.
.RE
.PP
\fBChristian Mack\fR <\&christian.mack@guardis.com\&>
.br
Guardis
.RS 4
Author.
.RE
.PP
\fBSandro Munda\fR <\&sandro.munda@guardis.com\&>
.br
Guardis
.RS 4
Author.
.RE
